module.exports = {
    getCommunityID(location) {

        let community = {
            1:"Afghanistan",
            2:"Albania",
            3:"Algeria",
            4:"American Samoa",
            5:"Andorra",
            6:"Angola",
            7:"Anguilla",
            8:"Antarctica",
            9:"Antigua and Barbuda",
            10:"Argentina",
            11:"Armenia",
            12:"Aruba",
            13:"Australia",
            14:"Austria",
            15:"Azerbaijan",
            16:"Bahamas",
            17:"Bahrain",
            18:"Bangladesh",
            19:"Barbados",
            20:"Belarus",
            21:"Belgium",
            22:"Belize",
            23:"Benin",
            24:"Bermuda",
            25:"Bhutan",
            26:"Bolivia",
            27:"Bosnia and Herzegovina",
            28:"Botswana",
            29:"Bouvet Island",
            30:"Brazil",
            31:"British Indian Ocean Territory",
            32:"Brunei Darussalam",
            33:"Bulgaria",
            34:"Burkina Faso",
            35:"Burundi",
            36:"Cambodia",
            37:"Cameroon",
            38:"Canada",
            39:"Cape Verde",
            40:"Cayman Islands",
            41:"Central African Republic",
            42:"Chad",
            43:"Chile",
            44:"China",
            45:"Christmas Island",
            46:"Cocos Keeling",
            47:"Colombia",
            48:"Comoros",
            49:"Congo",
            50:"Congo",
            51:"Cook Islands",
            52:"Costa Rica",
            53:"Cote DIvoire",
            54:"Croatia",
            55:"Cuba",
            56:"Cyprus",
            57:"Czech Republic",
            58:"Denmark",
            59:"Djibouti",
            60:"Dominica",
            61:"Dominican Republic",
            62:"Ecuador",
            63:"Egypt",
            64:"El Salvador",
            65:"Equatorial Guinea",
            66:"Eritrea",
            67:"Estonia",
            68:"Ethiopia",
            69:"Falkland Islands Malvinas",
            70:"Faroe Islands",
            71:"Fiji",
            72:"Finland",
            73:"France",
            74:"French Guiana",
            75:"French Polynesia",
            76:"French Southern Territories",
            77:"Gabon",
            78:"Gambia",
            79:"Georgia",
            80:"Germany",
            81:"Ghana",
            82:"Gibraltar",
            83:"Greece",
            84:"Greenland",
            85:"Grenada",
            86:"Guadeloupe",
            87:"Guam",
            88:"Guatemala",
            89:"Guinea",
            90:"Guinea-Bissau",
            91:"Guyana",
            92:"Haiti",
            93:"Heard Island and Mcdonald Islands",
            94:"Holy See Vatican City State",
            95:"Honduras",
            96:"Hong Kong",
            97:"Hungary",
            98:"Iceland",
            99:"India",
            100:"Indonesia",
            101:"Iran",
            102:"Iraq",
            103:"Ireland",
            104:"Israel",
            105:"Italy",
            106:"Jamaica",
            107:"Japan",
            108:"Jordan",
            109:"Kazakhstan",
            110:"Kenya",
            111:"Kiribati",
            112:"Korea",
            113:"Korea",
            114:"Kuwait",
            115:"Kyrgyzstan",
            116:"Lao Peoples Democratic Republic",
            117:"Latvia",
            118:"Lebanon",
            119:"Lesotho",
            120:"Liberia",
            121:"Libyan Arab Jamahiriya",
            122:"Liechtenstein",
            123:"Lithuania",
            124:"Luxembourg",
            125:"Macao",
            126:"Macedonia",
            127:"Madagascar",
            128:"Malawi",
            129:"Malaysia",
            130:"Maldives",
            131:"Mali",
            132:"Malta",
            133:"Marshall Islands",
            134:"Martinique",
            135:"Mauritania",
            136:"Mauritius",
            137:"Mayotte",
            138:"Mexico",
            139:"Micronesia",
            140:"Moldova",
            141:"Monaco",
            142:"Mongolia",
            143:"Montserrat",
            144:"Morocco",
            145:"Mozambique",
            146:"Myanmar",
            147:"Namibia",
            148:"Nauru",
            149:"Nepal",
            150:"Netherlands",
            151:"Netherlands Antilles",
            152:"New Caledonia",
            153:"New Zealand",
            154:"Nicaragua",
            155:"Niger",
            156:"Nigeria",
            157:"Niue",
            158:"Norfolk Island",
            159:"Northern Mariana Islands",
            160:"Norway",
            161:"Oman",
            162:"Pakistan",
            163:"Palau",
            164:"Palestinian Territory",
            165:"Panama",
            166:"Papua New Guinea",
            167:"Paraguay",
            168:"Peru",
            169:"Philippines",
            170:"Pitcairn",
            171:"Poland",
            172:"Portugal",
            173:"Puerto Rico",
            174:"Qatar",
            175:"Reunion",
            176:"Romania",
            177:"Russian Federation",
            178:"Rwanda",
            179:"Saint Helena",
            180:"Saint Kitts and Nevis",
            181:"Saint Lucia",
            182:"Saint Pierre and Miquelon",
            183:"Saint Vincent and the Grenadines",
            184:"Samoa",
            185:"San Marino",
            186:"Sao Tome and Principe",
            187:"Saudi Arabia",
            188:"Senegal",
            189:"Serbia and Montenegro",
            190:"Seychelles",
            191:"Sierra Leone",
            192:"Singapore",
            193:"Slovakia",
            194:"Slovenia",
            195:"Solomon Islands",
            196:"Somalia",
            197:"South Africa",
            198:"South Georgia and the South Sandwich Islands",
            199:"Spain",
            200:"Sri Lanka",
            201:"Sudan",
            202:"Suriname",
            203:"Svalbard and Jan Mayen",
            204:"Swaziland",
            205:"Sweden",
            206:"Switzerland",
            207:"Syrian Arab Republic",
            208:"Taiwan",
            209:"Tajikistan",
            210:"Tanzania",
            211:"Thailand",
            212:"Timor-Leste",
            213:"Togo",
            214:"Tokelau",
            215:"Tonga",
            216:"Trinidad and Tobago",
            217:"Tunisia",
            218:"Turkey",
            219:"Turkmenistan",
            220:"Turks and Caicos Islands",
            221:"Tuvalu",
            222:"Uganda",
            223:"Ukraine",
            224:"United Arab Emirates",
            225:"United Kingdom",
            225:"UK",
            226:"United States",
            227:"United States Minor Outlying Islands",
            228:"Uruguay",
            229:"Uzbekistan",
            230:"Vanuatu",
            231:"Venezuela",
            232:"Viet Nam",
            233:"Virgin Islands",
            234:"Virgin Islands",
            235:"Wallis and Futuna",
            236:"Western Sahara",
            237:"Yemen",
            238:"Zambia",
            239:"Zimbabwe",
            240:"Aberdeen",
            241:"St Albans",
            242:"Birmingham",
            243:"Bath",
            244:"Blackburn",
            245:"Bradford",
            246:"Bournemouth",
            247:"Bolton",
            248:"Brighton",
            249:"Bromley",
            250:"Bristol",
            251:"Belfast",
            252:"Carlisle",
            253:"Cambridge",
            254:"Cardiff",
            255:"Chester",
            256:"Chelmsford",
            257:"Colchester",
            258:"Croydon",
            259:"Canterbury",
            260:"Coventry",
            261:"Crewe",
            262:"Dartford",
            263:"Dundee",
            264:"Derby",
            265:"Dumfries",
            266:"Durham",
            267:"Darlington",
            268:"Doncaster",
            269:"Dorchester",
            270:"Dudley",
            271:"East London",
            272:"East Central London",
            273:"Edinburgh",
            274:"Enfield",
            275:"Exeter",
            276:"Falkirk",
            277:"Blackpool",
            278:"Glasgow",
            279:"Gloucester",
            280:"Guildford",
            281:"Harrow",
            282:"Huddersfield",
            283:"Harrogate",
            284:"Hemel Hempstead",
            285:"Hereford",
            286:"Outer Hebrides",
            287:"Hull",
            288:"Halifax",
            289:"Ilford",
            290:"Ipswich",
            291:"Inverness",
            292:"Kilmarnock",
            293:"Kingston upon Thames",
            294:"Kirkwall",
            295:"Kirkcaldy",
            296:"Liverpool",
            297:"Lancaster",
            298:"Llandrindod Wells",
            299:"Leicester",
            300:"Llandudno",
            301:"Lincoln",
            302:"Leeds",
            303:"Luton",
            304:"Manchester",
            305:"Rochester",
            306:"Milton Keynes",
            307:"Motherwell",
            308:"North London",
            309:"Newcastle upon Tyne",
            310:"Nottingham",
            311:"Northampton",
            312:"Newport",
            313:"Norwich",
            314:"North West London",
            315:"Oldham",
            316:"Oxford",
            317:"Paisley",
            318:"Peterborough",
            319:"Perth",
            320:"Plymouth",
            321:"Portsmouth",
            322:"Preston",
            323:"Reading",
            324:"Redhill",
            325:"Romford",
            326:"Sheffield",
            327:"Swansea",
            328:"South East London",
            329:"Stevenage",
            330:"Stockport",
            331:"Slough",
            332:"Sutton",
            333:"Swindon",
            334:"Southampton",
            335:"Salisbury",
            336:"Sunderland",
            337:"Southend-on-Sea",
            338:"Stoke-on-Trent",
            339:"South West London",
            340:"Shrewsbury",
            341:"Taunton",
            342:"Galashiels",
            343:"Telford",
            344:"Tunbridge Wells",
            345:"Torquay",
            346:"Truro",
            347:"Cleveland",
            348:"Twickenham",
            349:"Southall",
            350:"West London",
            351:"Warrington",
            352:"Western Central London",
            353:"Watford",
            354:"Wakefield",
            355:"Wigan",
            356:"Worcester",
            357:"Walsall",
            358:"Wolverhampton",
            359:"York",
            360:"Lerwick",
            361:"Guernsey",
            362:"Jersey",
            363:"Isle of Man"         
        }


       let r = Object.values(community).indexOf(location);  
       let k = Object.keys(community)[r];
        console.log("From Community ID's", k);
        return k;
    }
};